# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: stock_trading.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'stock_trading.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13stock_trading.proto\"#\n\rLookupRequest\x12\x12\n\nstock_name\x18\x01 \x01(\t\"7\n\x0eLookupResponse\x12\r\n\x05price\x18\x01 \x01(\x02\x12\x16\n\x0etrading_volume\x18\x02 \x01(\x05\"{\n\x0cTradeRequest\x12\x12\n\nstock_name\x18\x01 \x01(\t\x12\x10\n\x08quantity\x18\x02 \x01(\x05\x12%\n\x04type\x18\x03 \x01(\x0e\x32\x17.TradeRequest.TradeType\"\x1e\n\tTradeType\x12\x07\n\x03\x42UY\x10\x00\x12\x08\n\x04SELL\x10\x01\"\x1f\n\rTradeResponse\x12\x0e\n\x06status\x18\x01 \x01(\x05\"6\n\rUpdateRequest\x12\x12\n\nstock_name\x18\x01 \x01(\t\x12\x11\n\tnew_price\x18\x02 \x01(\x02\" \n\x0eUpdateResponse\x12\x0e\n\x06status\x18\x01 \x01(\x05\x32\x8c\x01\n\x0cStockTrading\x12)\n\x06Lookup\x12\x0e.LookupRequest\x1a\x0f.LookupResponse\x12&\n\x05Trade\x12\r.TradeRequest\x1a\x0e.TradeResponse\x12)\n\x06Update\x12\x0e.UpdateRequest\x1a\x0f.UpdateResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stock_trading_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LOOKUPREQUEST']._serialized_start=23
  _globals['_LOOKUPREQUEST']._serialized_end=58
  _globals['_LOOKUPRESPONSE']._serialized_start=60
  _globals['_LOOKUPRESPONSE']._serialized_end=115
  _globals['_TRADEREQUEST']._serialized_start=117
  _globals['_TRADEREQUEST']._serialized_end=240
  _globals['_TRADEREQUEST_TRADETYPE']._serialized_start=210
  _globals['_TRADEREQUEST_TRADETYPE']._serialized_end=240
  _globals['_TRADERESPONSE']._serialized_start=242
  _globals['_TRADERESPONSE']._serialized_end=273
  _globals['_UPDATEREQUEST']._serialized_start=275
  _globals['_UPDATEREQUEST']._serialized_end=329
  _globals['_UPDATERESPONSE']._serialized_start=331
  _globals['_UPDATERESPONSE']._serialized_end=363
  _globals['_STOCKTRADING']._serialized_start=366
  _globals['_STOCKTRADING']._serialized_end=506
# @@protoc_insertion_point(module_scope)
